config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :notes
  end

  get    '/signup',    to: 'users#new'
  post   '/signup',    to: 'users#create'
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'

  get    '/favorites', to: 'notes#index_favorites'
  get    '/notes',     to: 'notes#index'

  root 'welcome#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  validates :text, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :notes
  has_secure_password

  before_save do self.email.downcase! end
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, uniqueness: { case_sensitive: false },
                    format:     { with: VALID_EMAIL_REGEX },
                    presence:  true
  validates :password, length: { minimum: 6 }
  validates :display_name, presence: true, length: { maximum: 50 }

  def logged_in?
    persisted?
  end

  def display_name
    read_attribute(:display_name) || 'Guest'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= (User.find_by(id: session[:user_id]) || User.new)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  # GET /notes
  # GET /notes.json
  def index
    redirect_to login_path unless current_user.logged_in?
    @notes = current_user.notes
  end

  def index_favorites
    @favorites = current_user.notes.where favorite: true
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @notes = Note.find_by user_id: current_user.id
  end

  # GET /notes/new
  def new
    @note = current_user.notes.build
  end

  # GET /notes/1/edit
  def edit
    @current_user = current_user
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = current_user.notes.build note_params

    respond_to do |format|
      if @note.save
        format.html { redirect_to root_url, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to root_url, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    def set_user
      @current_user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:text, :favorite)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by email: user_params[:email]
    if @user && @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to login_path, flash: { error: 'Incorrect username or password' }
    end
  end

  def destroy
    if current_user
      session.delete :user_id
    end
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url
    else
      render 'users/new'
    end
  end

  private

  def user_params
    params.require(:user).permit :display_name, :email, :password, :password_confirmation
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_user

  def index
    redirect_to login_path unless current_user.logged_in?
  end

  private

  def set_user
    @current_user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= (User.find_by(id: session[:user_id]) || User.new)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  def left_notes
    favs = current_user.notes.where favorite: true
    favs = [] unless favs
    filled = fill_empty favs
    filled[0..4]
  end

  def right_notes
    favs = current_user.notes.where favorite: true
    favs = [] unless favs
    filled = fill_empty favs
    filled[5..9]
  end

  def fill_empty(notes)
    diff = 5 - notes.size
    diff.times do
      notes.push nil
    end
    return notes
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Eznote
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
  %body
    .content
      = yield

app/views/notes/_form.html.haml
= bootstrap_form_for [@current_user, @note], html: { class: 'note-form' } do |form|
  = form.text_area :text, placeholder: 'An important note...'
  = form.check_box :favorite
  = form.submit 'Done', class: 'btn btn-lg btn-primary btn-block'

app/views/notes/_note.html.haml
.note
  = link_to edit_user_note_path(@current_user, note), method: :get do
    %h4.note-text= note.text[0..40]

app/views/notes/_note_tab.html.haml
%li.note-tab
  %span.note-tab-content
    - if note
      = link_to edit_user_note_path(current_user, note), method: :get do 
        %p.note-text= note.text[0..10]
    - else 
      %p.note-text.no-bg= "&nbsp".html_safe

app/views/notes/edit.html.haml
= render partial: 'notes/form', locals: { note: @note }

app/views/notes/index.html.haml
%h1 All notes
= button_to 'New Note', new_user_note_path(@current_user), method: :get, class: 'btn btn-lg btn-primary btn-block'
- @notes.reverse.each do |note|
  = render note

app/views/notes/index_favorites.html.haml
%h1 Favorites
= button_to 'New Note', new_user_note_path(@current_user), method: :get, class: 'btn btn-lg btn-primary btn-block'
- @favorites.reverse.each do |note|
  = render note

app/views/notes/new.html.haml
= render partial: 'notes/form', locals: { note: @note }

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @note.text %>
</p>

<p>
  <strong>Favorite?:</strong>
  <%= @note.favorite? %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/users/new.html.haml
= bootstrap_form_for @user, url: signup_path, html: { class: 'form-signup' } do |form|
  = form.text_field :display_name, value: ''
  = form.email_field :email
  = form.password_field :password
  = form.password_field :password_confirmation, label: 'Password again'
  = form.submit 'Sign up', class: 'btn btn-lg btn-primary btn-block'

app/views/welcome/index.html.haml
.content
  .main-content
    %h2 EzNote
    .actions 
      = button_to 'All', notes_path, class: 'btn btn-lg btn-primary', method: :get
      = button_to 'New', new_user_note_path(@current_user), class: 'btn btn-lg btn-primary', method: :get
      = button_to 'Favorites', favorites_path, class: 'btn btn-lg btn-primary', method: :get
      = button_to 'Logout', logout_path, method: 'delete', class: 'btn btn-lg btn-primary'
  = button_to 'favs', root_url, method: :get, remote: true, class: 'btn btn-lg btn-primary', id: 'fav-button'
  %ul.note-tab-column-left
    - left_notes.each do |note|
      = render partial: 'notes/note_tab', locals: { note: note }
  %ul.note-tab-column-right
    - right_notes.each do |note|
      = render partial: 'notes/note_tab', locals: { note: note }